# Generated by Django 6.0.1 on 2026-01-31 00:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especiaria',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='especiaria',
            name='quantidade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
