# Generated by Django 6.0.1 on 2026-01-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_especiaria_descricao_especiaria_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponibilidade', models.BooleanField()),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponibilidade', models.BooleanField()),
                ('descricao', models.TextField(blank=True)),
                ('diretor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quadro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponibilidade', models.BooleanField()),
                ('descricao', models.TextField(blank=True)),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='especiaria',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='especiaria',
            name='disponibilidade',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
