# Generated by Django 6.0.1 on 2026-01-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_artefato_filme_quadro_remove_especiaria_quantidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('disponibilidade', models.BooleanField()),
                ('descricao', models.TextField(blank=True)),
                ('isbn', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Filme',
        ),
        migrations.AlterField(
            model_name='especiaria',
            name='disponibilidade',
            field=models.BooleanField(blank=True),
        ),
    ]
