# Generated by Django 6.0.1 on 2026-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_livro_delete_filme_alter_especiaria_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especiaria',
            name='disponibilidade',
            field=models.BooleanField(),
        ),
    ]
